development:
  adapter: mysql2
  database: christmasdev
  username: christmas
  password: christmas
  host: localhost
  port: 3306

test:
  adapter: mysql2
  database: christmastest
  username: christmastest
  password: christmas
  host: localhost
  port: 3306

production:
  adapter: mysql2
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
